# Generated by Django 4.0.6 on 2022-07-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='honam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('uploadedFile', models.FileField(upload_to='')),
                ('dir_name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=10)),
                ('weather', models.CharField(max_length=20)),
            ],
        ),
    ]
